
development:
  adapter: postgresql
  encoding: unicode
  database: plants_dev

test:
  adapter: postgresql
  encoding: unicode
  database: no_such_thing

production:
  adapter: postgresql
  encoding: unicode
  database: no_such_thing
